FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /source

COPY *.csproj .
RUN dotnet restore -r linux-x64 /p:PublishReadyToRun=true

COPY . ./
RUN dotnet publish -c release -o /app -r linux-x64 --self-contained true /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishSingleFile=true

FROM mcr.microsoft.com/dotnet/runtime-deps:6.0-focal-amd64
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["./ServerApi"]